### ISSUE TITLE
[朋友圈服务器]调用内容时，返回的friendcomment有问题

### ISSUE THREAD

**Issue by yuanff** [shcalm/Moments#34]
friendcomment的name有问题
{
10-26 11:08:43.631 11949 12075 D CustomerFragment:         "content": "Hcf", 
10-26 11:08:43.631 11949 12075 D CustomerFragment:         "friendcomment": [
10-26 11:08:43.631 11949 12075 D CustomerFragment:           {
10-26 11:08:43.631 11949 12075 D CustomerFragment:             "comment": "Ghf", 
10-26 11:08:43.631 11949 12075 D CustomerFragment:             "isReplyName": null, 
10-26 11:08:43.631 11949 12075 D CustomerFragment:             "replyId": 2, 
10-26 11:08:43.631 11949 12075 D CustomerFragment:             "replyName": 5
10-26 11:08:43.631 11949 12075 D CustomerFragment:           }
10-26 11:08:43.631 11949 12075 D CustomerFragment:         ], 
10-26 11:08:43.631 11949 12075 D CustomerFragment:         "friendpraise": [
10-26 11:08:43.631 11949 12075 D CustomerFragment:           5
10-26 11:08:43.631 11949 12075 D CustomerFragment:         ], 
10-26 11:08:43.631 11949 12075 D CustomerFragment:         "id": 14, 
10-26 11:08:43.631 11949 12075 D CustomerFragment:         "sendtime": "2015-10-20 09:25", 
10-26 11:08:43.631 11949 12075 D CustomerFragment:         "uname": "tt", 
10-26 11:08:43.631 11949 12075 D CustomerFragment:         "urls": [], 
10-26 11:08:43.631 11949 12075 D CustomerFragment:         "usericon": "https://avatars2.githubusercontent.com/u/1171281?v=3&s=460"
10-26 11:08:43.631 11949 12075 D CustomerFragment:       }

**Comment by shcalm** [comment]
fix
