### ISSUE TITLE
朋友圈问题

### ISSUE THREAD

**Issue by yuanff** [shcalm/Moments#6]
目前朋友圈查询数据，用的是http://moments.daoapp.io/api/v1.0/posts/?page="+i + "&classid=" + (groupIdList.size() == 0 ?"" :groupIdList.get(0))， 其中上传了page和classid字段。
发朋友圈用的是：（也上传了classid）
HttpPost httppost = new HttpPost("http://moments.daoapp.io/api/v1.0/posts/");
            httppost.setHeader("Authorization", "Basic " + MyApplication.getBase64Code());

```
        JSONObject jsonParam = new JSONObject();
        JSONArray array = new JSONArray();
        array.addAll(list);

        jsonParam.put("content", params[0]);// 标题
        jsonParam.put("urls", array);
        jsonParam.put("class_id", (classIdList != null && classIdList.size() == 0) ? "" :classIdList.get(0));
        jsonParam.put("timestamp", new SimpleDateFormat("yyyy-MM-dd HH:mm").format(new Date()));
```

**Comment by shcalm** [comment]
是的。
